### ISSUE TITLE
Set up Read the Docs

### ISSUE THREAD

**Issue by ah-** [wintoncode/winton-kafka-streams#13]
We want nice documentation!

Register an account on readthedocs.io and hook it up with GitHub: https://tutos.readthedocs.io/en/latest/source/git_rtd.html

**Comment by llawall** [comment]
I'm already on this. I'm already part way through the process :)

**Comment by llawall** [comment]
There is a webhook added to trigger the build but note that it the build is currently failing.

**Comment by llawall** [comment]
Failures now due to Python 3.6 requirement and lack of support for this yet on RtD.

**Comment by llawall** [comment]
I have requested access to the updated build image with Pytgon 3.6 support.
