### ISSUE TITLE
Feature request: Avro support

### ISSUE THREAD

**Issue by gavrie** [wintoncode/winton-kafka-streams#33]
Now that PR #32 has been merged and issue #26 has been resolved, can we expect support for Avro serialization/deserialization? I'd really like, for interoperability with Java Kafka Streams, to be able to process topics that use Avro together with the Confluent Schema Registry.

**Comment by sambott** [comment]
Nice idea @gavrie , I'll take a look.

**Comment by gavrie** [comment]
This would be a tremendous boon for companies like ours that use both Java and Python, and would like to have interoperable data. I suspect that a lot of people would find this useful.

**Comment by sambott** [comment]
Added initial implementation as part of PR #42
