### ISSUE TITLE
How to send using streams

### ISSUE THREAD

**Issue by vlad1777d** [wintoncode/winton-kafka-streams#39]
Hello.

How to send a message to a topic using streams ?
I'm trying to figure it out second day, reading sources, trying to make logic chains, looking to dir() outputs, but all time I get different errors.
In examples such task was absent, also I tried to copy behavior from tests - it didn't give the result.

My log story: https://pastebin.com/Rf0wYSf0
My draft code: https://pastebin.com/90jcPcaV (with all my attempts)
My code, which after receiving some message sends duplicate: https://pastebin.com/HxXNXV3F

How do I tried sending messages using streams:
 - created confluent_kafka Producer
 - manually sent message through RecordCollector (and he called Producer)
 - manually sent message through Processor (which called RecordCollector)
 - automatic sending message by Processor in case receiving of some message: https://pastebin.com/HxXNXV3F

But it still uses Producer.
My task is to send messages using streams, not by Producer.

Thank you.

Best regards,
Vladislav

**Comment by ah-** [comment]
Hi Vladislav,

have a look at the wordcount example here: https://github.com/wintoncode/winton-kafka-streams/blob/master/examples/wordcount/example.py#L56 

To write back out, you just need to create a topology with a sink node, like this:
```
 sink('output-count', 'wks-wordcount-example-count', 'count')
```

That creates a sink named 'output-count', sending data from the 'count' processor to the 'wks-wordcount-example-count' topic.

**Comment by vlad1777d** [comment]
@ah- , understood, thank you very much.
I looked at it, but didn't understood what it does.
Now all is well =)
